routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'FrontController@index')->name('home');

// binding de model
Route::get('post/{post}', 'FrontController@show');

Route::get('posts/{post_type}', 'FrontController@showPostByType')->name('post_type');

Route::get('contact', 'FrontController@contact')->name('contact');

Route::post('search','FrontController@search');

Route::post('email', 'FrontController@sendMail');

Auth::routes();

Route::middleware(['auth'])->group(function(){
    Route::resource('admin/post', 'PostController');
    Route::post('delete', 'PostController@deleteAll')->name('deleteAll');
    Route::get('trash','PostController@trash')->name('trash');
    Route::post('destroy', 'PostController@destroy')->name('destroy');
    Route::get('restore/{id}', 'PostController@restore')->name('restore');
});


//Route::get('post/{type}/{name?}', 'FrontController@showPostByTypes')->name('type'); pour le référencement

resources/views/partials/admin_menu.blade.php
@if(Auth::check())
<ul class="navbar-nav justify-content-end">
<li class="nav-item"><a class="navbar-brand" href="{{route('post.index')}}">Dashboard</a></li>
<li class="nav-item"><a class="navbar-brand" href="{{ route('logout') }}"onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Se déconnecter</a></li>
<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    @csrf 
    </form>
    @else
    
    @endif
</ul>

resources/views/partials/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/partials/flash.blade.php
@if(Session::has('message'))
<div class="alert">
    <p>{{Session::get('message')}}</p>
</div>
@endif

resources/views/partials/form_search.blade.php
<form action="{{ action('FrontController@search') }}" method="POST" class="form-inline">
@csrf
<input class="form-control mr-sm-2" type="search" placeholder="Rechercher" aria-label="Search" value="" name="word">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

resources/views/partials/menu.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light mt-4 mb-4">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
          <a class="navbar-brand" href="{{ route('home')}}">Accueil</a>
          </li>
        <li class="nav-item">
            <a class="navbar-brand" href="{{route('post_type', 'stage')}}">Stage</a>
        </li>
        <li class="nav-item">
            <a class="navbar-brand" href="{{route('post_type', 'formation')}}">Formation</a>
        </li>
        <li class="nav-item">
            <a class="navbar-brand" href="{{route('contact')}}">Contact</a>
        </li>
        @include('partials.form_search')
      </ul>
      
      @include('partials.admin_menu')
    </div>
  </nav>