routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'FrontController@index')->name('home');

// binding de model
Route::get('post/{post}', 'FrontController@show');

Route::get('posts/{post_type}', 'FrontController@showPostByType')->name('post_type');

Route::get('contact', 'FrontController@contact')->name('contact');

Route::post('search','FrontController@search');

Route::post('email', 'FrontController@sendMail');

Auth::routes();

Route::middleware(['auth'])->group(function(){
    Route::resource('admin/post', 'PostController');
    Route::post('delete', 'PostController@deleteAll')->name('deleteAll');
    Route::get('trash','PostController@trash')->name('trash');
    Route::post('destroy', 'PostController@destroy')->name('destroy');
    Route::get('restore/{id}', 'PostController@restore')->name('restore');
});


//Route::get('post/{type}/{name?}', 'FrontController@showPostByTypes')->name('type'); pour le référencement

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{

    use SoftDeletes;

    protected $guarded = ['title_image', 'picture'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
    
    public function setCategorieIdAttribute($value){
       
        if($value == 0){
            $this->attributes['categorie_id'] = null;
        }else{

            $this->attributes['categorie_id'] = $value;
        }

    }

    public function scopeType($query, $type){
        return $query->where('post_type', $type);
    }

    public function scopeSearch($query, string $word){
        return $query->where('title', 'like', "%$word%");
    }

    public function scopePublished($query){
        return $query->where('status', 'published');
    }

    public function categorie(){
        return $this->belongsTo(Category::class);
    }

    public function picture(){
        return $this->hasOne(Picture::class);
    }
    
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Category;
use App\Picture;
use App\Http\Requests\PostRequest;
use Storage;
use Cache;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * AFFICHER TOUS LES POSTS
     */

    protected $paginate = 10;

    public function index()
    {
        $posts = Post::paginate($this->paginate);

        return view('back.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     * CREER UN POST
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id');

       return view('back.post.create', compact('categories'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     * 
     */

    public function store(PostRequest $request)
    {

        $post = Post::create($request->all());
        $im = $request->file('picture');

        if(!empty($im)){
            
            $link = $request->file('picture')->store('/.');
            $post->picture()->create([
            'link' => $link,
            'title' => $request->title_image ?? $request->title
            ]);
        }

        Cache::flush();

        return redirect()->route('post.index')->with('message', 'Votre post a bien été créé !');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     * Montrer un livre
     */
    public function show(Post $post)
    {

        return view('back.post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        
        $categories = Category::pluck('name', 'id')->all();
       return view('back.post.edit', compact ('post', 'categories'));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {

        $post->update($request->all());

        $im = $request->file('picture');

        if(!empty($im)){
            
            $link = $request->file('picture')->store('./');

            if(!is_null($post->picture)){

                Storage::disk('local')->delete($post->picture->link);

                $post->picture()->delete();
            }
            $post->picture()->create([
                'link' => $link,
                'title' => $request->title_image?? $request->title

            ]);
        }

        Cache::flush();

        return redirect()->route('post.index')->with('message','Le post a été modifié !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $collection = collect($request->destroy);
        $collection->each(function($id, $key){
            $post = Post::onlyTrashed()->find($id)->forceDelete();
        });

        Cache::flush();

        return redirect()->route('trash')->with('message','Les posts ont été supprimés avec succès !');
    }

    //PUT POST IN TRASH
    public function deleteAll(Request $request){

        $collection = collect($request->delete);
        $collection->each(function($id, $key){

            $post = Post::find($id)->delete();

        });

        Cache::flush();

        return redirect()->route('post.index')->with('message','Les posts ont été placés dans la corbeille !');

    }

    //POST IN TRASH
    public function trash(){

        $trashedPosts = Post::onlyTrashed()->paginate($this->paginate);
        
        return view('back.post.trash',compact('trashedPosts'));
    }

    //RESTORE POST
    public function restore(int $id){
        $post = Post::onlyTrashed()
                    ->where('id', $id)
                    ->restore();

        return redirect()->route('post.index')->with('message','Les posts ont été restaurés correctement !');
    }

}

resources/views/back/post/create.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-6">

    <h1>Créer un post</h1>

    <form action="{{route('post.store')}}" method="post" enctype="multipart/form-data">
    @csrf

    <div class="form">
            <div class="form-group">
                <label for="title">Titre :</label>
                <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Titre de la formation ou du stage">
                @if($errors->has('title')) <span class="error bg-warning text-warning">{{$errors->first('title')}}</span>
                @endif
            </div>

            <div class="form-group">
                    <label for="description">Description :</label>
                    <textarea type="text" name="description" class="form-control" >{{ old('description') }}</textarea>
                    @if($errors->has('description')) <span class="error bg-warning text-warning">{{$errors->first('description')}}</span>
                    @endif
                </div>
            </div>

            <div class="form-select">
                    <label for="categorie">Catégorie :</label>
                    <select id="categorie" name="categorie_id">
                    <option value="0" {{is_null(old('categorie_id'))? 'selected' : ''}}>Aucune catégorie</option>
                    @forelse($categories as $id => $name)
                        @if(old('categorie_id') == $id)
                        <option value="{{ $id }}" selected>{{ $name }}</option>
                        @else
                        <option value="{{ $id }}">{{ $name }}</option>
                        @endif
                    @empty
                        <option>Aucune catégorie</option>
                    @endforelse
                     </select>
                </div>
            

                <div class="form-check form-check-inline">
                        <label for="post_type">Type:</label>
                        <input class="form-check-input" type="radio" id="post_type"
                        @if(old('post_type') == 'formation')
                        checked
                        @endif
                        name="post_type" value="formation">
                        <label class="form-check-label" for="post_type">Formation</label>
                        <input class="form-check-input" type="radio" id="post_type"
                        @if(old('post_type') == 'stage')
                        checked
                        @endif
                        name="post_type" value="stage">
                        <label class="form-check-label" for="post_type">Stage</label>
                    </div>

                    <div class="form-group">
                            <label for="price">Prix (en euros) :</label>
                            <textarea type="number" name="price" class="form-control">{{ old('price') }}</textarea>
                            @if($errors->has('price'))
                            <span class="error bg-warning text-warning">{{$errors->first('price')}}</span>
                            @endif
                        </div>
                    
                        <div class="form-group">
                                <label for="number_student">Nombre d'élève admis :</label>
                                <textarea type="number" name="number_student" class="form-control"> {{ old('number_student') }}</textarea>
                                @if($errors->has('number_student'))
                                <span class="error bg-warning text-warning">{{$errors->first('number_student')}}</span>
                                @endif
                            </div>

</div><!-- /. col-6 -->

<div class="row justify-content-center">
        <div class="col-md-6">
            <button type="submit" class="btn btn-primary">Ajouter un post</button>
            
            @include('partials.errors')

            <div class="input-radio">
                    <label for="status">Status :</label>
                    <input type="radio" id="status" @if(old('status')=='published') checked @endif name="status" value="published" checked>
                    <label class="form-check-label" for="post_type">Publié</label>
                    <input type="radio" id="status" @if(old('status')=='unpublished') checked @endif name="status" value="unpublished" >
                    <label class="form-check-label" for="post_type">Non publié</label>
                </div>

                <div class="form-group">
                        <label for="start_date">Début :</label>
                        <input type="date" id="start_date" name="start_date" value={{ old('start_date') }}>
                </div>
                                
                <div class="form-group">
                        <label for="end_date">Fin :</label>
                        <input type="date" id="end_date" name="end_date" value={{ old('end_date') }}>
                </div>

                    
                    <div class="form-group">

                        <label for="title_image">Titre image :</label>

                        <input type="text" name="title_image" value="{{ old('title_image') }}">

                        <input class="file" type="file" name="picture" id="title_image">

                        @if($errors->has('picture'))
                        <span class="error bg-warning text-warning">{{$errors->first('picture')}}</span>
                        @endif
                    </div>
                    

        </div><!-- /.col md 6 -->
</div><!-- /.row .justify-content-center -->
</form>
</div>{{-- /.row --}}
@endsection

resources/views/back/post/edit.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-6">

    <h1>Modifier le stage/ la formation</h1>

    <form action="{{route('post.update', $post->id)}}" method="POST" enctype="multipart/form-data">
    @csrf
    {{method_field('PUT')}}

        <div class="form">
            <div class="form-group">
                <label for="title">Titre :</label>
                <input type="text" name="title" value="{{$post->title}}" class="form-control" id="title" placeholder="Titre de la formation ou du stage">
                @if($errors->has('title')) <span class="error bg-warning text-warning">{{$errors->first('title')}}</span>
                @endif
            </div>

            <div class="form-group">
                <label for="description">Description :</label>
                <textarea type="text" name="description" class="form-control" >{{$post->description}}</textarea>
                @if($errors->has('description')) <span class="error bg-warning text-warning">{{$errors->first('description')}}</span>
                @endif
            </div>
        </div>
                    
        <div class="form-select">
            <label for="categorie">Catégorie :</label>
            <select id="categorie" name="categorie_id">
            <option value="0" {{is_null($post->categorie)? 'selected' : ''}}>Aucune catégorie</option>
            @foreach($categories as $id => $name)
                <option {{ ($post->categorie_id == $id) ? 'selected' : '' }} value="{{$id}}">{{$name}}</option>
            @endforeach
             </select>
        </div>
                    
        <div class="form-check form-check-inline">
            <label for="post_type">Type :</label>
            <input class="form-check-input" type="radio" id="post_type"
            @if($post->post_type == 'formation')
            checked
            @endif
            name="post_type" value="formation">
            <label class="form-check-label" for="post_type">Formation</label>
            <input class="form-check-input" type="radio" id="post_type"
            @if($post->post_type == 'stage')
            checked
            @endif
            name="post_type" value="stage">
            <label class="form-check-label" for="post_type">Stage</label>
        </div>

        <div class="form-group">
            <label for="price">Prix (en euros) :</label>
            <textarea type="number" name="price" class="form-control">{{$post->price}}</textarea>
            @if($errors->has('price'))
            <span class="error bg-warning text-warning">{{$errors->first('price')}}</span>
            @endif
        </div>

        <div class="form-group">
            <label for="number_student">Nombre d'élève admis :</label>
            <textarea type="number" name="number_student" class="form-control">{{$post->number_student}}</textarea>
            @if($errors->has('number_student'))
            <span class="error bg-warning text-warning">{{$errors->first('number_student')}}</span>
            @endif
        </div>
                    
</div><!-- /. col-6 -->

<div class="row justify-content-center">
<div class="col-md-6">
    <button type="submit" class="btn btn-primary">Modifiez</button>
    
    <div class="input-radio">
        <label for="status">Status :</label>
        <input type="radio" id="status" @if(old('status')=='published') checked @endif name="status" value="published" checked>
        <label class="form-check-label" for="post_type">Publié</label>
        <input type="radio" id="status" @if(old('status')=='unpublished') checked @endif name="status" value="unpublished" >
        <label class="form-check-label" for="post_type">Non publié</label>
    </div>

    <div class="form-group">
            <label for="start_date">Début :</label>
            <input type="date" id="start_date" name="start_date" value={{ $post->start_date }}>
    </div>
                    
    <div class="form-group">
            <label for="end_date">Fin :</label>
            <input type="date" id="end_date" name="end_date" value={{ $post->end_date }}>
    </div>

    @if($post->picture)
    <div class="form-group">
        <p>Image associée :</p>
        <label for="title_image">Titre image :</label>
        <input type="text" name="title_image" value="{{ $post->picture->title }}">

        <input class="file" type="file" name="picture" id="title_image">

        @if($errors->has('picture'))
        <span class="error bg-warning text-warning">{{$errors->first('picture')}}</span>
        @endif
    </div>

    <div class="form-group">
        <img width="200" src="{{ url('images', $post->picture->link) }}" alt="">
    </div>
    @endif
</div><!-- /.col md 6 -->
</div><!-- /.row .justify-content-center -->
</form>
</div>{{-- /.row --}}
@endsection

resources/views/back/post/index.blade.php
@extends('layouts.master')

@section('content')

@include('partials.flash')


<a href="{{route('post.create')}}" class="btn btn-info mb-4">
Ajouter un post</a>
<a href="{{route('trash')}}" class="btn btn-info mb-4">
  Corbeille</a>

{{$posts->links()}}
<form class="delete" method="post" action="{{ route('deleteAll') }}">
    @csrf
    <button type="submit" class="btn btn-primary mb-2 float-right">Mettre dans la corbeille</button> 
<table class="table table-striped">
    <thead class="table-primary">
        <tr>
            <th>Titre</th>
            <th>Prix</th>
            <th>Début</th>
            <th>Fin</th>
            <th>Nombre d'élèves</th>
            <th>Type</th>
            <th>Date de publication</th>
            <th>Date de création</th>
            <th>Date de mise à jour</th>
            <th>Status</th>
            <th>Modifier</th>
            <th>Voir</th>
            <th>Supprimer</th>
        </tr> {{-- End of tr, container of the dashboard's first line --}}
    </thead>
    <tbody>
    @forelse($posts as $post)
    <tr>
      <td>
        <a href="{{route('post.edit', $post->id)}}">{{$post->title}}</a>
      </td>

      <td>{{ $post->price}}</td>

      <td>{{ $post->start_date}}</td>

      <td>{{ $post->end_date}}</td>

      <td>{{ $post->number_student}}</td>

      <td>{{ $post->post_type}}</td>

      <td>{{$post->published_at}}</td>

      <td>{{$post->created_at}}</td>

      <td>{{$post->updated_at}}</td>

      <td>
      @if($post->status == 'published')
        <button type="button" class="btn btn-success">Publié</button>
      @else
      <button type="button" class="btn btn-warning">Non publié</button>
      @endif
      </td>

      <td>
        <a href="{{route('post.edit', $post->id)}}"><i class="far fa-edit"></i></a>
      </td>
      
      <td>
        <a href="{{route('post.show', $post->id)}}"><i class="fas fa-eye"></i></a></td>
      <td>
        <input type="checkbox" class="form-check-input" id="delete_all" name="delete[]" value="{{ $post->id }}">
      </td>
    </tr>
    @empty
        Aucun titre
    @endforelse
  </tbody>{{-- End of tbody, container of the table --}}
</table>{{-- /.table .table-striped --}}

<button type="submit" class="btn btn-primary mb-2 float-right">Mettre dans la corbeille</button> 
</form>

{{$posts->links()}}
@endsection

@section('scripts')
    @parent
        <script src="{{asset('js/confirm.js')}}"></script>
@endsection

resources/views/back/post/show.blade.php
@extends('layouts.master')
@section('content')
<article>
    @if(is_null($post) == false)
        <h1>{{$post->title}}</h1>
            <div class="row mt-3">
                @if(is_null($post->picture) == false)
                    <div class="col">
                        <a href="#" class="thumbnail">
                            <img width="300" src="{{asset('images/'.$post->picture->link)}}" alt="{{$post->picture->title}}">
                        </a>
                    </div> {{-- /.col --}}
                @endif
                    <div class="col-8">
                        <h4>Description :</h4>
                        <p>{{$post->description}}</p>
                    </div>
            </div>{{-- row mt-3 --}}

            <div class="row mt-4">

            <div class="col">
                <h4>Début: </h4>
                <p>{{$post->start_date}}</p>
            </div>

            <div class="col">
                <h4>Prix: </h4>
                <p>{{$post->price}}€</p>
            </div>

            <div class="col">
                <h4>Fin: </h4>
                <p>{{$post->end_date}}</p>
            </div>

            <div class="col">
                <h4>Nombre d'élève: </h4>
                <p>{{$post->number_student}}</p>
            </div>

            <div class="col">
                <h4>Type: </h4>
                <p>{{$post->post_type}}</p>
            </div>

            <div class="col">
                <h4>Catégorie: </h4>
                <p>{{$post->categorie->name}}</p>
            </div>

            <div class="col">
                    <h4>Date de création: </h4>
                    <p>{{$post->created_at}}</p>
                </div>
                <div class="col">
                        <h4>Date de mise à jour : </h4>
                        <p>{{$post->updated_at}}</p>
                    </div>
            

            @else
            <h3>Désolé aucune formation, aucun stage trouvé</h3>
            @endif
            
        </div> {{-- /.row --}}
</article> {{-- End of article --}}
@endsection 

resources/views/back/post/trash.blade.php
@extends('layouts.master')

@section('content')
@include('partials.flash')

{{$trashedPosts->links()}}
<form class="destroy" method="post" action="{{ route('destroy') }}">
      @csrf
      <button type="submit" class="btn btn-primary mb-2 float-right">Supprimer définitivement</button> 
<table class="table table-striped">
    <thead class="table-primary">
        <tr>
            <th>Titre</th>
            <th>Prix</th>
            <th>Début</th>
            <th>Fin</th>
            <th>Nombre d'élèves</th>
            <th>Type</th>
            <th>Date de publication</th>
            <th>Date de création</th>
            <th>Date de mise à jour</th>
            <th>Status</th>
            <th>Voir</th>
            <th>Supprimer</th>
            <th>Restaurer</th>
        </tr> {{-- End of tr, container of the dashboard's first line --}}
    </thead>
    <tbody>
    @forelse($trashedPosts as $key=>$trashedPost)
    <tr>
      <td>{{$trashedPost->title}}</td>

      <td>{{ $trashedPost->price}}</td>

      <td>{{ $trashedPost->start_date}}</td>

      <td>{{ $trashedPost->end_date}}</td>

      <td>{{ $trashedPost->number_student}}</td>

      <td>{{ $trashedPost->post_type}}</td>

      <td>{{$trashedPost->published_at}}</td>

      <td>{{$trashedPost->created_at}}</td>

      <td>{{$trashedPost->updated_at}}</td>

      <td>
        @if($trashedPost->status == 'published')
          <button type="button" class="btn btn-success">Publié</button>
        @else
          <button type="button" class="btn btn-warning">Non publié</button>
        @endif
      </td>

      <td>
        <a href="{{route('post.show', $trashedPost->id)}}"><i class="fas fa-eye"></i></a>
      </td>

      <td>
        <input type="checkbox" class="form-check-input" id="destroy" name="destroy[]" value="{{ $trashedPost->id }}">
      </td>

      <td>
          <a href="{{ action('PostController@restore', ['id' => $trashedPost->id]) }}" class="btn btn-danger">Restaurer</a>
      </td>
    </tr>
    @empty
        Aucun titre
    @endforelse
  </tbody>{{-- End of tbody, container of the table --}}
</table>{{-- /.table .table-striped --}}

<button type="submit" class="btn btn-primary mb-2 float-right">Supprimer définitivement</button> 
</form>

{{$trashedPosts->links()}}
@endsection

@section('scripts')
    @parent
        <script src="{{asset('js/confirm.js')}}"></script>
@endsection